version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Install dpkg and fakeroot
          command: |
            sudo apt-get update -y
            sudo dpkg --add-architecture i386 && sudo apt-get update -y
            sudo apt-get install -y dpkg fakeroot wine32 wine64
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate Builds
          command: npm run build
          
      - run:
          name: Generate Windows binaries
          command: npm run win

      - store_artifacts:
          path: ~/repo/dist
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
